//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToastStream.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToastStream.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ToastStream について に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutToastStream {
            get {
                return ResourceManager.GetString("AboutToastStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ToastStreamのアクセスを許可して、PINを入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllowAccessToToastStream {
            get {
                return ResourceManager.GetString("AllowAccessToToastStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動的にアップデートする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllowAutoUpdate {
            get {
                return ResourceManager.GetString("AllowAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時にToastStreamのアップデートを確認する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllowUpdateCheck {
            get {
                return ResourceManager.GetString("AllowUpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API key（通常は入力不要です） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string APIkey_OnlyIfNecessary {
            get {
                return ResourceManager.GetString("APIkey_OnlyIfNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API secret（通常は入力不要です） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string APIsecret_OnlyIfNecessary {
            get {
                return ResourceManager.GetString("APIsecret_OnlyIfNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ 一部の設定は再起動後に有効になります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppliedAfterRestart {
            get {
                return ResourceManager.GetString("AppliedAfterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   適用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証済みです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Authenticated {
            get {
                return ResourceManager.GetString("Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証状況 :  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthProgress {
            get {
                return ResourceManager.GetString("AuthProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トークンを取得できませんでした。しばらく待ってから再度認証してみてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CantGetAccessToken {
            get {
                return ResourceManager.GetString("CantGetAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証URLを取得できませんでした。しばらく待ってから再度認証してみてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CantGetAuthentificationURL {
            get {
                return ResourceManager.GetString("CantGetAuthentificationURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証されていません。 ①のボタンをクリックして認証してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotYetAuthenticated {
            get {
                return ResourceManager.GetString("NotYetAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像ファイル(*.jpg;*.jpeg;*.png;*.gif)|*.jpg;*.jpeg;*.png;*.gif|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileDialog_Filter {
            get {
                return ResourceManager.GetString("OpenFileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ① 認証ページをブラウザで開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenTheAuthentificationURL {
            get {
                return ResourceManager.GetString("OpenTheAuthentificationURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   APIキーのオーバーライド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OverridesAPIkeys {
            get {
                return ResourceManager.GetString("OverridesAPIkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ② PINを入力して認証を完了する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PINtoCompleteAuthentification {
            get {
                return ResourceManager.GetString("PINtoCompleteAuthentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他人へのリプライを全て受信する（トーストを占有する可能性が高くなります） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReceiveAllReplies {
            get {
                return ResourceManager.GetString("ReceiveAllReplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツイートする画像の選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイムライン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツイート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tweet {
            get {
                return ResourceManager.GetString("Tweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
